**IS 170 LAB 1- Nick Garcia & Jorge Angon**

In [3]:
import pandas as pd # importing both panda and numpy library
import numpy as np

In [4]:
from google.colab import files #starting code to import files into google colab
uploaded=files.upload()#Gives you prompt to upload dataset
df=pd.read_csv('machine-readable-business-employment-data-sep-2025-quarter.csv')#must recognize correct file before uploading dataset
df.head(100)#displays the first 100 rows

Saving machine-readable-business-employment-data-sep-2025-quarter.csv to machine-readable-business-employment-data-sep-2025-quarter.csv

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BDCQ.SEA1AS,2020.09,99657.0,NaN,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,NaN,NaN
96,BDCQ.SEA1AS,2020.12,98469.0,NaN,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,NaN,NaN
97,BDCQ.SEA1AS,2021.03,97449.0,NaN,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,NaN,NaN
98,BDCQ.SEA1AS,2021.06,97336.0,NaN,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,NaN,NaN
99,BDCQ.SEA1AS,2021.09,97770.0,NaN,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,NaN,NaN

In [5]:
df.isnull().sum()#Shows the number of NA in each column

Series_reference        0
Period                  0
Data_value           2839
Suppressed          22446
STATUS                  0
UNITS                   0
Magnitude               0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2          0
Series_title_3          0
Series_title_4      25285
Series_title_5      25285
dtype: int64

In [6]:
df.fillna(value=0, inplace=True) #Fills in NA spots and replace it with 0
df.isnull().sum() #shows zero NA by replacing it with 0

Series_reference    0
Period              0
Data_value          0
Suppressed          0
STATUS              0
UNITS               0
Magnitude           0
Subject             0
Group               0
Series_title_1      0
Series_title_2      0
Series_title_3      0
Series_title_4      0
Series_title_5      0
dtype: int64

In [7]:
df.head(100)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,0,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0
1,BDCQ.SEA1AA,2011.09,78324.0,0,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0
2,BDCQ.SEA1AA,2011.12,85850.0,0,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0
3,BDCQ.SEA1AA,2012.03,90743.0,0,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0
4,BDCQ.SEA1AA,2012.06,81780.0,0,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BDCQ.SEA1AS,2020.09,99657.0,0,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,0.0,0.0
96,BDCQ.SEA1AS,2020.12,98469.0,0,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,0.0,0.0
97,BDCQ.SEA1AS,2021.03,97449.0,0,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,0.0,0.0
98,BDCQ.SEA1AS,2021.06,97336.0,0,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,0.0,0.0
99,BDCQ.SEA1AS,2021.09,97770.0,0,R,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Seasonally adjusted,0.0,0.0

In [8]:
from sklearn.preprocessing import LabelEncoder #This is importing the LabelEncoder library from sklearn
le = LabelEncoder() #this creates or sets an intance for le for label encoder
label= le.fit_transform(df['STATUS'])#putting .fit_transformed fits label
label

array([1, 1, 1, ..., 1, 1, 1])

In [9]:
df.drop("STATUS", axis=1, inplace=True) #droping the STATUS column from df for now
df["STATUS"] = label #putting the STATUS back into the dataset ut attaching the array to it with the same name
df.head()

,Series_reference,Period,Data_value,Suppressed,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5,STATUS
0,BDCQ.SEA1AA,2011.06,80078.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0,1
1,BDCQ.SEA1AA,2011.09,78324.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0,1
2,BDCQ.SEA1AA,2011.12,85850.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0,1
3,BDCQ.SEA1AA,2012.03,90743.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0,1
4,BDCQ.SEA1AA,2012.06,81780.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,0.0,1

In [10]:
#Same process but using for the Series_title_3 column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label =le.fit_transform(df['Series_title_3'])
label

array([0, 0, 0, ..., 0, 0, 0])

In [11]:
#Same process but using the Series_title_3 column
df.drop("Series_title_3", axis=1, inplace=True)
df["Series_title_3"] = label
df.head(100)

,Series_reference,Period,Data_value,Suppressed,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_4,Series_title_5,STATUS,Series_title_3
0,BDCQ.SEA1AA,2011.06,80078.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,1,0
1,BDCQ.SEA1AA,2011.09,78324.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,1,0
2,BDCQ.SEA1AA,2011.12,85850.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,1,0
3,BDCQ.SEA1AA,2012.03,90743.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,1,0
4,BDCQ.SEA1AA,2012.06,81780.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BDCQ.SEA1AS,2020.09,99657.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,2,1
96,BDCQ.SEA1AS,2020.12,98469.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,2,1
97,BDCQ.SEA1AS,2021.03,97449.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,2,1
98,BDCQ.SEA1AS,2021.06,97336.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,2,1
99,BDCQ.SEA1AS,2021.09,97770.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",0.0,0.0,2,1

In [13]:
#This code renaranges the columns
# Originally, STATUS was at the very end so I moved it in front of the series
old_cols=df.columns.values
new_cols=['Series_reference', 'Period', 'Data_value', 'Suppressed', 'UNITS', 'Magnitude', 'Subject', 'Group', 'STATUS', 'Series_title_1', 'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5']
df=df.reindex(columns=new_cols)
df

,Series_reference,Period,Data_value,Suppressed,UNITS,Magnitude,Subject,Group,STATUS,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,1,Filled jobs,"Agriculture, Forestry and Fishing",0,0.0,0.0
1,BDCQ.SEA1AA,2011.09,78324.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,1,Filled jobs,"Agriculture, Forestry and Fishing",0,0.0,0.0
2,BDCQ.SEA1AA,2011.12,85850.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,1,Filled jobs,"Agriculture, Forestry and Fishing",0,0.0,0.0
3,BDCQ.SEA1AA,2012.03,90743.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,1,Filled jobs,"Agriculture, Forestry and Fishing",0,0.0,0.0
4,BDCQ.SEA1AA,2012.06,81780.0,0,Number,0,Business Data Collection - BDC,Industry by employment variable,1,Filled jobs,"Agriculture, Forestry and Fishing",0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,BDCQ.SEE3999A,2017.06,0.0,Y,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,1,Filled jobs (workplace location based),Area Outside Territorial Authority,0,0.0,0.0
25281,BDCQ.SEE3999A,2017.09,0.0,Y,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,1,Filled jobs (workplace location based),Area Outside Territorial Authority,0,0.0,0.0
25282,BDCQ.SEE3999A,2017.12,0.0,Y,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,1,Filled jobs (workplace location based),Area Outside Territorial Authority,0,0.0,0.0
25283,BDCQ.SEE3999A,2018.03,0.0,Y,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,1,Filled jobs (workplace location based),Area Outside Territorial Authority,0,0.0,0.0
25284,BDCQ.SEE3999A,2018.06,0.0,Y,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,1,Filled jobs (workplace location based),Area Outside Territorial Authority,0,0.0,0.0

In [14]:
#This prints out new names for columns I decided to change like "period" to "Date" and changing all series titles to just "Title"
print(df.rename(columns={'Period':'Date', 'Series_title_1':'Title_1', 'Series_title_2':'Title_2', 'Series_title_3':'Title_3', "Series_title_4":'Title_4', 'Series_title_5':'Title_5' }))

      Series_reference     Date  Data_value Suppressed   UNITS  Magnitude  \
0          BDCQ.SEA1AA  2011.06     80078.0          0  Number          0
1          BDCQ.SEA1AA  2011.09     78324.0          0  Number          0
2          BDCQ.SEA1AA  2011.12     85850.0          0  Number          0
3          BDCQ.SEA1AA  2012.03     90743.0          0  Number          0
4          BDCQ.SEA1AA  2012.06     81780.0          0  Number          0
...                ...      ...         ...        ...     ...        ...
25280    BDCQ.SEE3999A  2017.06         0.0          Y  Number          0
25281    BDCQ.SEE3999A  2017.09         0.0          Y  Number          0
25282    BDCQ.SEE3999A  2017.12         0.0          Y  Number          0
25283    BDCQ.SEE3999A  2018.03         0.0          Y  Number          0
25284    BDCQ.SEE3999A  2018.06         0.0          Y  Number          0

                              Subject  \
0      Business Data Collection - BDC
1      Business Data Collection - BDC
2      Business Data Collection - BDC
3      Business Data Collection - BDC
4      Business Data Collection - BDC
...                               ...
25280  Business Data Collection - BDC
25281  Business Data Collection - BDC
25282  Business Data Collection - BDC
25283  Business Data Collection - BDC
25284  Business Data Collection - BDC

                                              Group  STATUS  \
0                   Industry by employment variable       1
1                   Industry by employment variable       1
2                   Industry by employment variable       1
3                   Industry by employment variable       1
4                   Industry by employment variable       1
...                                             ...     ...
25280  Territorial authority by employment variable       1
25281  Territorial authority by employment variable       1
25282  Territorial authority by employment variable       1
25283  Territorial authority by employment variable       1
25284  Territorial authority by employment variable       1

                                      Title_1  \
0                                 Filled jobs
1                                 Filled jobs
2                                 Filled jobs
3                                 Filled jobs
4                                 Filled jobs
...                                       ...
25280  Filled jobs (workplace location based)
25281  Filled jobs (workplace location based)
25282  Filled jobs (workplace location based)
25283  Filled jobs (workplace location based)
25284  Filled jobs (workplace location based)

                                  Title_2  Title_3  Title_4  Title_5
0       Agriculture, Forestry and Fishing        0      0.0      0.0
1       Agriculture, Forestry and Fishing        0      0.0      0.0
2       Agriculture, Forestry and Fishing        0      0.0      0.0
3       Agriculture, Forestry and Fishing        0      0.0      0.0
4       Agriculture, Forestry and Fishing        0      0.0      0.0
...                                   ...      ...      ...      ...
25280  Area Outside Territorial Authority        0      0.0      0.0
25281  Area Outside Territorial Authority        0      0.0      0.0
25282  Area Outside Territorial Authority        0      0.0      0.0
25283  Area Outside Territorial Authority        0      0.0      0.0
25284  Area Outside Territorial Authority        0      0.0      0.0

[25285 rows x 14 columns]