IS 170 LAB 1 - Nick Garcia & Jorge Angon

In [4]:
import pandas as pd
import numpy as np

In [5]:
#Uploading dataset to google colab
#Dataset includes data about students classes, academic level, etc. It shows how addicted they can be to their phones.
from google.colab import files
uploaded=files.upload()
df=pd.read_csv('Students Social Media Addiction.csv')
df.head(100)

Saving Students Social Media Addiction.csv to Students Social Media Addiction.csv

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,19,Female,Undergraduate,Qatar,4.9,TikTok,Yes,5.7,6,Single,3,7
96,97,18,Male,High School,Kuwait,5.7,Snapchat,Yes,5.3,5,In Relationship,4,8
97,98,22,Female,Graduate,Bahrain,2.8,LinkedIn,No,7.1,8,Complicated,1,4
98,99,20,Male,Undergraduate,Oman,4.6,Instagram,Yes,5.9,6,Single,3,7
99,100,21,Female,Undergraduate,Jordan,5.4,TikTok,Yes,5.5,5,In Relationship,4,8

In [6]:
#There are no NA in this data set as everything shows 0 null columns
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64

In [7]:
#Using the Label Encoder to transform the affects academic performance because it fits the true/false category
#it displays the array. It will replace all the trues with 0s and false with 1s
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
label=le.fit_transform(df['Affects_Academic_Performance'])
label

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1])

In [8]:
#It will drop the columns and basically put it back into table with the new labels
df.drop("Affects_Academic_Performance", axis=1, inplace=True)
df["Affects_Academic_Performance"]=label
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score,Affects_Academic_Performance
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,6.5,6,In Relationship,3,8,1
1,2,22,Male,Graduate,India,2.1,Twitter,7.5,8,Single,0,3,0
2,3,20,Female,Undergraduate,USA,6.0,TikTok,5.0,5,Complicated,4,9,1
3,4,18,Male,High School,UK,3.0,YouTube,7.0,7,Single,1,4,0
4,5,21,Male,Graduate,Canada,4.5,Facebook,6.0,6,In Relationship,2,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,7.2,7,In Relationship,2,5,0
701,702,23,Male,Graduate,Russia,6.8,Instagram,5.9,4,Single,5,9,1
702,703,21,Female,Undergraduate,China,5.6,WeChat,6.7,6,In Relationship,3,7,1
703,704,24,Male,Graduate,Japan,4.3,Twitter,7.5,8,Single,2,4,0
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,6.3,5,Single,4,8,1

In [9]:
#We decided to do the same for Gender as there was only two genders listed
#This is the same process as before for affects adameci performance
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
label=le.fit_transform(df['Gender'])
label

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0])

In [10]:
#Same process as it drops Genders and reenters the table with the label encoder
df.drop("Gender", axis=1, inplace=True)
df["Gender"]=label
df

,Student_ID,Age,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score,Affects_Academic_Performance,Gender
0,1,19,Undergraduate,Bangladesh,5.2,Instagram,6.5,6,In Relationship,3,8,1,0
1,2,22,Graduate,India,2.1,Twitter,7.5,8,Single,0,3,0,1
2,3,20,Undergraduate,USA,6.0,TikTok,5.0,5,Complicated,4,9,1,0
3,4,18,High School,UK,3.0,YouTube,7.0,7,Single,1,4,0,1
4,5,21,Graduate,Canada,4.5,Facebook,6.0,6,In Relationship,2,7,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Undergraduate,Italy,4.7,TikTok,7.2,7,In Relationship,2,5,0,0
701,702,23,Graduate,Russia,6.8,Instagram,5.9,4,Single,5,9,1,1
702,703,21,Undergraduate,China,5.6,WeChat,6.7,6,In Relationship,3,7,1,0
703,704,24,Graduate,Japan,4.3,Twitter,7.5,8,Single,2,4,0,1
704,705,19,Undergraduate,Poland,6.2,Facebook,6.3,5,Single,4,8,1,0

In [11]:
#Since we dropped the last two columns they reappear at the very end of the tabel and out of order
#We used this code reorder the table and place "Gender" and "Affects_Academic_Performance"
old_cols=df.columns.values
new_cols=['Student_ID', 'Age', 'Gender','Academic_Level', 'Country', 'Avg_Daily_Usage_Hours', 'Most_Used_Platform', 'Sleep_Hours_Per_Night', 'Mental_Health_Score', 'Relationship_Status', 'Conflicts_Over_Social_Media', 'Affects_Academic_Performance', 'Addicted_Score'  ]
df=df.reindex(columns=new_cols)
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Affects_Academic_Performance,Addicted_Score
0,1,19,0,Undergraduate,Bangladesh,5.2,Instagram,6.5,6,In Relationship,3,1,8
1,2,22,1,Graduate,India,2.1,Twitter,7.5,8,Single,0,0,3
2,3,20,0,Undergraduate,USA,6.0,TikTok,5.0,5,Complicated,4,1,9
3,4,18,1,High School,UK,3.0,YouTube,7.0,7,Single,1,0,4
4,5,21,1,Graduate,Canada,4.5,Facebook,6.0,6,In Relationship,2,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,0,Undergraduate,Italy,4.7,TikTok,7.2,7,In Relationship,2,0,5
701,702,23,1,Graduate,Russia,6.8,Instagram,5.9,4,Single,5,1,9
702,703,21,0,Undergraduate,China,5.6,WeChat,6.7,6,In Relationship,3,1,7
703,704,24,1,Graduate,Japan,4.3,Twitter,7.5,8,Single,2,0,4
704,705,19,0,Undergraduate,Poland,6.2,Facebook,6.3,5,Single,4,1,8

In [12]:
#This just renames the columns names
#For example, we renamed Avg_Daily_Usage_Hours to Avg_Daily_Hours
print(df.rename(columns={'Avg_Daily_Usage_Hours':'Avg_Daily_Hours'}))

     Student_ID  Age  Gender Academic_Level     Country  Avg_Daily_Hours  \
0             1   19       0  Undergraduate  Bangladesh              5.2
1             2   22       1       Graduate       India              2.1
2             3   20       0  Undergraduate         USA              6.0
3             4   18       1    High School          UK              3.0
4             5   21       1       Graduate      Canada              4.5
..          ...  ...     ...            ...         ...              ...
700         701   20       0  Undergraduate       Italy              4.7
701         702   23       1       Graduate      Russia              6.8
702         703   21       0  Undergraduate       China              5.6
703         704   24       1       Graduate       Japan              4.3
704         705   19       0  Undergraduate      Poland              6.2

    Most_Used_Platform  Sleep_Hours_Per_Night  Mental_Health_Score  \
0            Instagram                    6.5                    6
1              Twitter                    7.5                    8
2               TikTok                    5.0                    5
3              YouTube                    7.0                    7
4             Facebook                    6.0                    6
..                 ...                    ...                  ...
700             TikTok                    7.2                    7
701          Instagram                    5.9                    4
702             WeChat                    6.7                    6
703            Twitter                    7.5                    8
704           Facebook                    6.3                    5

    Relationship_Status  Conflicts_Over_Social_Media  \
0       In Relationship                            3
1                Single                            0
2           Complicated                            4
3                Single                            1
4       In Relationship                            2
..                  ...                          ...
700     In Relationship                            2
701              Single                            5
702     In Relationship                            3
703              Single                            2
704              Single                            4

     Affects_Academic_Performance  Addicted_Score
0                               1               8
1                               0               3
2                               1               9
3                               0               4
4                               1               7
..                            ...             ...
700                             0               5
701                             1               9
702                             1               7
703                             0               4
704                             1               8

[705 rows x 13 columns]

In [ ]:
#There was no need to drop null values or replace them in this dataset because it contained none
#We could not use one-hot encoding because not all columns were a boolean and mostly floats and integers
#Data normalization would not work with this dataset because it contains mostly floats and could not be executed