Lab 3: Association rules

Jorge Angon, Valerie Jimenez

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

df = pd.read_csv("Supermart.csv")
df.head()
#call libraries that are needed ands read the csv file and display it

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(df.isnull().sum()) #Shows missing values. output shows that there are no missing values.

Order ID         0
Customer Name    0
Category         0
Sub Category     0
City             0
Order Date       0
Region           0
Sales            0
Discount         0
Profit           0
State            0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Make a new table called "products"
# Each row is a basket of Sub Category items

df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["OrderMonth"] = df["Order Date"].dt.to_period("M")

df = (
    df.groupby(["Customer Name", "OrderMonth"])["Sub Category"]
      .apply(lambda x: ",".join(sorted(set(x))))
      .reset_index(name="products")
)

# Keep only the column we need
df = df[["products"]]
df.head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

                                          products
0                                          Chicken
1                             Health Drinks,Mutton
2                      Fresh Fruits,Masalas,Spices
3                  Edible Oil & Ghee,Mutton,Spices
4  Edible Oil & Ghee,Health Drinks,Organic Staples

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df.shape #Shows the rows and columns

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

(2268, 1)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Turns into a list of items
data = list(df["products"].apply(lambda x: x.split(",")))
data

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

[['Chicken'],
 ['Health Drinks', 'Mutton'],
 ['Fresh Fruits', 'Masalas', 'Spices'],
 ['Edible Oil & Ghee', 'Mutton', 'Spices'],
 ['Edible Oil & Ghee', 'Health Drinks', 'Organic Staples'],
 ['Chocolates', 'Cookies', 'Rice', 'Spices'],
 ['Chicken', 'Chocolates', 'Cookies', 'Dals & Pulses', 'Mutton'],
 ['Chocolates', 'Fresh Fruits', 'Health Drinks'],
 ['Atta & Flour',
  'Chocolates',
  'Dals & Pulses',
  'Health Drinks',
  'Mutton',
  'Rice',
  'Soft Drinks'],
 ['Atta & Flour',
  'Chocolates',
  'Dals & Pulses',
  'Fish',
  'Masalas',
  'Soft Drinks'],
 ['Cookies', 'Dals & Pulses'],
 ['Organic Vegetables'],
 ['Biscuits', 'Chocolates'],
 ['Breads & Buns', 'Chicken', 'Fresh Fruits'],
 ['Biscuits', 'Health Drinks', 'Soft Drinks'],
 ['Chocolates', 'Fresh Fruits'],
 ['Breads & Buns', 'Dals & Pulses', 'Fresh Fruits', 'Organic Fruits'],
 ['Fresh Vegetables', 'Soft Drinks', 'Spices'],
 ['Breads & Buns'],
 ['Cookies',
  'Fish',
  'Noodles',
  'Organic Fruits',
  'Organic Vegetables',
  'Spices'],
 ['Chocolates', 'Health Drinks', 'Noodles'],
 ['Health Drinks', 'Soft Drinks'],
 ['Dals & Pulses', 'Edible Oil & Ghee'],
 ['Cookies', 'Edible Oil & Ghee', 'Organic Vegetables'],
 ['Noodles'],
 ['Breads & Buns',
  'Fresh Vegetables',
  'Mutton',
  'Organic Fruits',
  'Organic Vegetables',
  'Spices'],
 ['Dals & Pulses', 'Fresh Fruits', 'Fresh Vegetables', 'Organic Vegetables'],
 ['Cakes', 'Cookies', 'Eggs', 'Rice'],
 ['Breads & Buns',
  'Chicken',
  'Dals & Pulses',
  'Fresh Vegetables',
  'Organic Staples',
  'Organic Vegetables',
  'Spices'],
 ['Cakes', 'Cookies', 'Health Drinks', 'Soft Drinks'],
 ['Cakes',
  'Fresh Vegetables',
  'Noodles',
  'Organic Vegetables',
  'Soft Drinks',
  'Spices'],
 ['Biscuits',
  'Cakes',
  'Cookies',
  'Health Drinks',
  'Organic Staples',
  'Soft Drinks'],
 ['Biscuits', 'Cookies', 'Fish', 'Masalas', 'Noodles'],
 ['Noodles', 'Organic Fruits', 'Soft Drinks'],
 ['Atta & Flour', 'Biscuits', 'Noodles', 'Soft Drinks'],
 ['Atta & Flour',
  'Biscuits',
  'Cakes',
  'Chocolates',
  'Cookies',
  'Rice',
  'Spices'],
 ['Atta & Flour',
  'Biscuits',
  'Chocolates',
  'Organic Fruits',
  'Organic Vegetables',
  'Soft Drinks'],
 ['Atta & Flour',
  'Breads & Buns',
  'Fresh Fruits',
  'Fresh Vegetables',
  'Noodles',
  'Organic Vegetables'],
 ['Atta & Flour', 'Fish', 'Masalas', 'Noodles'],
 ['Biscuits', 'Edible Oil & Ghee', 'Fish', 'Health Drinks', 'Rice', 'Spices'],
 ['Cookies',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Fish',
  'Health Drinks',
  'Noodles',
  'Spices'],
 ['Breads & Buns', 'Eggs'],
 ['Breads & Buns',
  'Cakes',
  'Chocolates',
  'Edible Oil & Ghee',
  'Fresh Vegetables',
  'Health Drinks',
  'Masalas',
  'Organic Staples'],
 ['Cakes',
  'Chocolates',
  'Fresh Vegetables',
  'Noodles',
  'Organic Fruits',
  'Organic Staples',
  'Organic Vegetables',
  'Soft Drinks',
  'Spices'],
 ['Cakes', 'Chicken', 'Noodles', 'Organic Staples', 'Soft Drinks'],
 ['Cookies', 'Organic Vegetables'],
 ['Health Drinks', 'Soft Drinks', 'Spices'],
 ['Breads & Buns', 'Cakes', 'Fish'],
 ['Cakes', 'Edible Oil & Ghee'],
 ['Breads & Buns', 'Fresh Vegetables', 'Mutton', 'Organic Fruits'],
 ['Breads & Buns',
  'Health Drinks',
  'Masalas',
  'Organic Staples',
  'Organic Vegetables',
  'Rice'],
 ['Cookies', 'Eggs', 'Fresh Vegetables', 'Rice', 'Soft Drinks', 'Spices'],
 ['Atta & Flour', 'Breads & Buns', 'Dals & Pulses', 'Edible Oil & Ghee'],
 ['Dals & Pulses'],
 ['Health Drinks', 'Rice', 'Soft Drinks', 'Spices'],
 ['Cakes',
  'Chocolates',
  'Cookies',
  'Eggs',
  'Fish',
  'Mutton',
  'Organic Fruits',
  'Spices'],
 ['Chocolates',
  'Edible Oil & Ghee',
  'Fresh Vegetables',
  'Health Drinks',
  'Organic Staples'],
 ['Breads & Buns', 'Chocolates'],
 ['Chocolates'],
 ['Atta & Flour', 'Biscuits', 'Cookies', 'Soft Drinks'],
 ['Fresh Fruits', 'Mutton'],
 ['Organic Fruits', 'Organic Staples', 'Organic Vegetables'],
 ['Biscuits',
  'Breads & Buns',
  'Cookies',
  'Noodles',
  'Organic Fruits',
  'Soft Drinks'],
 ['Organic Fruits'],
 ['Biscuits', 'Edible Oil & Ghee'],
 ['Cakes', 'Cookies', 'Edible Oil & Ghee', 'Fish', 'Fresh Vegetables'],
 ['Health Drinks'],
 ['Biscuits', 'Eggs', 'Organic Staples'],
 ['Cakes', 'Noodles', 'Organic Staples'],
 ['Atta & Flour', 'Organic Staples'],
 ['Chocolates', 'Organic Vegetables'],
 ['Atta & Flour', 'Biscuits', 'Cakes', 'Organic Fruits', 'Rice', 'Spices'],
 ['Atta & Flour',
  'Breads & Buns',
  'Health Drinks',
  'Mutton',
  'Soft Drinks',
  'Spices'],
 ['Atta & Flour',
  'Breads & Buns',
  'Chocolates',
  'Edible Oil & Ghee',
  'Fresh Vegetables'],
 ['Edible Oil & Ghee', 'Health Drinks', 'Soft Drinks'],
 ['Chicken', 'Health Drinks'],
 ['Atta & Flour', 'Breads & Buns', 'Fresh Vegetables', 'Organic Vegetables'],
 ['Breads & Buns', 'Dals & Pulses', 'Mutton', 'Soft Drinks'],
 ['Cookies', 'Dals & Pulses', 'Edible Oil & Ghee', 'Fresh Fruits'],
 ['Cakes',
  'Dals & Pulses',
  'Fresh Vegetables',
  'Health Drinks',
  'Masalas',
  'Organic Fruits',
  'Organic Staples'],
 ['Cakes', 'Edible Oil & Ghee'],
 ['Cakes',
  'Chocolates',
  'Edible Oil & Ghee',
  'Health Drinks',
  'Masalas',
  'Organic Fruits',
  'Organic Staples',
  'Soft Drinks'],
 ['Atta & Flour',
  'Cakes',
  'Masalas',
  'Mutton',
  'Noodles',
  'Organic Vegetables'],
 ['Breads & Buns',
  'Cakes',
  'Chocolates',
  'Cookies',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Fresh Fruits',
  'Health Drinks',
  'Masalas'],
 ['Biscuits', 'Cakes', 'Chocolates', 'Edible Oil & Ghee'],
 ['Chicken', 'Cookies', 'Dals & Pulses', 'Edible Oil & Ghee', 'Health Drinks'],
 ['Chicken', 'Chocolates', 'Cookies', 'Masalas', 'Noodles', 'Organic Fruits'],
 ['Atta & Flour', 'Dals & Pulses', 'Noodles'],
 ['Chicken', 'Spices'],
 ['Health Drinks', 'Mutton'],
 ['Edible Oil & Ghee'],
 ['Breads & Buns', 'Rice'],
 ['Fresh Fruits'],
 ['Breads & Buns', 'Cookies', 'Health Drinks', 'Rice'],
 ['Atta & Flour',
  'Breads & Buns',
  'Chicken',
  'Dals & Pulses',
  'Fresh Fruits',
  'Masalas',
  'Noodles'],
 ['Atta & Flour', 'Cakes', 'Fresh Vegetables'],
 ['Breads & Buns',
  'Edible Oil & Ghee',
  'Noodles',
  'Organic Vegetables',
  'Spices'],
 ['Atta & Flour', 'Cookies'],
 ['Edible Oil & Ghee', 'Spices'],
 ['Cookies', 'Rice'],
 ['Biscuits', 'Health Drinks'],
 ['Atta & Flour', 'Biscuits', 'Edible Oil & Ghee', 'Eggs'],
 ['Cakes', 'Noodles', 'Rice', 'Spices'],
 ['Chocolates', 'Cookies', 'Dals & Pulses'],
 ['Atta & Flour',
  'Breads & Buns',
  'Cakes',
  'Chicken',
  'Cookies',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Fresh Fruits',
  'Rice'],
 ['Eggs', 'Spices'],
 ['Masalas'],
 ['Biscuits',
  'Cakes',
  'Chicken',
  'Fresh Vegetables',
  'Health Drinks',
  'Masalas',
  'Noodles',
  'Spices'],
 ['Biscuits', 'Edible Oil & Ghee'],
 ['Biscuits', 'Masalas', 'Soft Drinks'],
 ['Breads & Buns', 'Cookies', 'Fish', 'Organic Fruits'],
 ['Chicken', 'Cookies', 'Edible Oil & Ghee', 'Health Drinks'],
 ['Biscuits',
  'Breads & Buns',
  'Chocolates',
  'Fish',
  'Health Drinks',
  'Organic Fruits'],
 ['Chicken', 'Cookies', 'Fresh Fruits', 'Mutton'],
 ['Masalas', 'Organic Fruits', 'Spices'],
 ['Atta & Flour',
  'Biscuits',
  'Breads & Buns',
  'Dals & Pulses',
  'Fresh Fruits',
  'Masalas',
  'Rice'],
 ['Eggs', 'Mutton', 'Organic Staples'],
 ['Chicken', 'Edible Oil & Ghee', 'Health Drinks', 'Mutton', 'Rice'],
 ['Eggs', 'Mutton', 'Noodles', 'Organic Vegetables', 'Spices'],
 ['Biscuits', 'Health Drinks', 'Soft Drinks'],
 ['Health Drinks'],
 ['Biscuits', 'Chicken', 'Cookies', 'Eggs', 'Health Drinks', 'Mutton'],
 ['Atta & Flour',
  'Dals & Pulses',
  'Fresh Fruits',
  'Noodles',
  'Organic Fruits',
  'Soft Drinks'],
 ['Chicken', 'Eggs', 'Fish', 'Fresh Fruits', 'Noodles'],
 ['Dals & Pulses',
  'Edible Oil & Ghee',
  'Fresh Vegetables',
  'Organic Fruits',
  'Soft Drinks',
  'Spices'],
 ['Breads & Buns', 'Organic Staples'],
 ['Atta & Flour', 'Chicken', 'Health Drinks', 'Organic Staples'],
 ['Atta & Flour',
  'Breads & Buns',
  'Chocolates',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Eggs',
  'Fresh Vegetables',
  'Organic Fruits',
  'Rice',
  'Soft Drinks'],
 ['Biscuits', 'Cakes', 'Organic Fruits', 'Organic Staples', 'Soft Drinks'],
 ['Biscuits', 'Dals & Pulses', 'Fish', 'Noodles', 'Soft Drinks'],
 ['Biscuits',
  'Breads & Buns',
  'Cakes',
  'Chocolates',
  'Dals & Pulses',
  'Eggs',
  'Masalas',
  'Organic Staples',
  'Rice',
  'Soft Drinks'],
 ['Breads & Buns', 'Chocolates', 'Soft Drinks'],
 ['Fresh Vegetables', 'Organic Vegetables', 'Soft Drinks'],
 ['Cookies', 'Eggs', 'Health Drinks', 'Noodles', 'Spices'],
 ['Cookies'],
 ['Eggs'],
 ['Biscuits',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Health Drinks',
  'Organic Fruits'],
 ['Cakes', 'Edible Oil & Ghee', 'Organic Vegetables'],
 ['Biscuits',
  'Cakes',
  'Dals & Pulses',
  'Eggs',
  'Fish',
  'Mutton',
  'Soft Drinks'],
 ['Biscuits', 'Fresh Fruits', 'Organic Staples'],
 ['Cakes',
  'Cookies',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Fresh Vegetables',
  'Health Drinks',
  'Organic Staples',
  'Organic Vegetables',
  'Rice',
  'Soft Drinks'],
 ['Breads & Buns', 'Cakes', 'Cookies', 'Dals & Pulses', 'Edible Oil & Ghee'],
 ['Mutton', 'Soft Drinks'],
 ['Atta & Flour', 'Cookies'],
 ['Edible Oil & Ghee'],
 ['Cookies', 'Dals & Pulses', 'Eggs', 'Mutton', 'Rice', 'Soft Drinks'],
 ['Atta & Flour', 'Cakes', 'Fresh Vegetables'],
 ['Breads & Buns', 'Fresh Fruits', 'Health Drinks', 'Masalas'],
 ['Health Drinks'],
 ['Masalas', 'Soft Drinks', 'Spices'],
 ['Breads & Buns',
  'Cookies',
  'Edible Oil & Ghee',
  'Masalas',
  'Mutton',
  'Organic Vegetables',
  'Spices'],
 ['Atta & Flour', 'Fresh Vegetables', 'Organic Staples'],
 ['Eggs', 'Spices'],
 ['Biscuits', 'Cakes', 'Fresh Vegetables', 'Masalas', 'Organic Fruits'],
 ['Fresh Vegetables'],
 ['Organic Staples'],
 ['Chocolates', 'Organic Fruits', 'Rice', 'Soft Drinks'],
 ['Cookies', 'Dals & Pulses', 'Edible Oil & Ghee', 'Fish'],
 ['Noodles', 'Organic Vegetables', 'Rice', 'Soft Drinks'],
 ['Chicken', 'Health Drinks'],
 ['Edible Oil & Ghee', 'Masalas', 'Noodles', 'Organic Staples'],
 ['Chicken',
  'Chocolates',
  'Cookies',
  'Fish',
  'Fresh Vegetables',
  'Noodles',
  'Organic Staples',
  'Rice'],
 ['Breads & Buns', 'Spices'],
 ['Cookies',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Mutton',
  'Organic Staples',
  'Soft Drinks',
  'Spices'],
 ['Biscuits',
  'Breads & Buns',
  'Cookies',
  'Dals & Pulses',
  'Organic Fruits',
  'Soft Drinks'],
 ['Rice'],
 ['Fresh Vegetables', 'Noodles'],
 ['Breads & Buns', 'Chocolates', 'Organic Vegetables', 'Rice'],
 ['Organic Vegetables', 'Spices'],
 ['Cakes', 'Chicken', 'Cookies', 'Edible Oil & Ghee', 'Organic Vegetables'],
 ['Biscuits',
  'Chicken',
  'Cookies',
  'Edible Oil & Ghee',
  'Eggs',
  'Fish',
  'Mutton',
  'Spices'],
 ['Biscuits',
  'Breads & Buns',
  'Eggs',
  'Fresh Fruits',
  'Health Drinks',
  'Organic Vegetables'],
 ['Cakes', 'Chicken', 'Dals & Pulses', 'Health Drinks', 'Rice'],
 ['Dals & Pulses',
  'Fish',
  'Health Drinks',
  'Masalas',
  'Noodles',
  'Organic Staples',
  'Soft Drinks'],
 ['Cookies', 'Eggs', 'Noodles', 'Rice'],
 ['Atta & Flour',
  'Biscuits',
  'Breads & Buns',
  'Cookies',
  'Organic Staples',
  'Rice',
  'Soft Drinks'],
 ['Biscuits', 'Fresh Fruits', 'Masalas', 'Mutton', 'Organic Staples'],
 ['Health Drinks', 'Organic Fruits'],
 ['Fish'],
 ['Cakes', 'Cookies', 'Noodles', 'Rice', 'Spices'],
 ['Biscuits', 'Cookies'],
 ['Biscuits', 'Breads & Buns', 'Fresh Vegetables', 'Health Drinks', 'Masalas'],
 ['Masalas', 'Spices'],
 ['Fish'],
 ['Breads & Buns'],
 ['Biscuits',
  'Chicken',
  'Cookies',
  'Fresh Fruits',
  'Mutton',
  'Noodles',
  'Rice',
  'Soft Drinks',
  'Spices'],
 ['Cakes', 'Cookies', 'Noodles', 'Spices'],
 ['Biscuits',
  'Chicken',
  'Cookies',
  'Dals & Pulses',
  'Fresh Vegetables',
  'Health Drinks'],
 ['Atta & Flour',
  'Breads & Buns',
  'Chocolates',
  'Dals & Pulses',
  'Soft Drinks',
  'Spices'],
 ['Biscuits', 'Health Drinks', 'Noodles'],
 ['Cakes', 'Fish', 'Organic Vegetables'],
 ['Chocolates', 'Dals & Pulses'],
 ['Atta & Flour', 'Breads & Buns', 'Cakes', 'Chicken', 'Masalas', 'Noodles'],
 ['Atta & Flour',
  'Biscuits',
  'Breads & Buns',
  'Fresh Vegetables',
  'Health Drinks'],
 ['Biscuits', 'Eggs', 'Noodles'],
 ['Atta & Flour',
  'Breads & Buns',
  'Cakes',
  'Masalas',
  'Noodles',
  'Organic Fruits',
  'Organic Staples'],
 ['Fish', 'Health Drinks', 'Mutton'],
 ['Atta & Flour',
  'Biscuits',
  'Breads & Buns',
  'Cookies',
  'Fresh Vegetables',
  'Masalas'],
 ['Organic Fruits', 'Organic Staples'],
 ['Atta & Flour', 'Chocolates', 'Dals & Pulses'],
 ['Atta & Flour',
  'Breads & Buns',
  'Dals & Pulses',
  'Fresh Vegetables',
  'Health Drinks',
  'Organic Fruits',
  'Rice'],
 ['Cookies', 'Eggs', 'Soft Drinks'],
 ['Fresh Fruits', 'Organic Staples', 'Soft Drinks'],
 ['Biscuits', 'Edible Oil & Ghee'],
 ['Fresh Vegetables', 'Health Drinks', 'Organic Staples', 'Soft Drinks'],
 ['Breads & Buns',
  'Dals & Pulses',
  'Health Drinks',
  'Organic Staples',
  'Organic Vegetables'],
 ['Cookies', 'Dals & Pulses', 'Health Drinks', 'Soft Drinks'],
 ['Atta & Flour',
  'Breads & Buns',
  'Fresh Vegetables',
  'Health Drinks',
  'Organic Staples'],
 ['Breads & Buns'],
 ['Cakes',
  'Dals & Pulses',
  'Fresh Fruits',
  'Health Drinks',
  'Noodles',
  'Organic Staples',
  'Rice',
  'Spices'],
 ['Cookies', 'Edible Oil & Ghee', 'Masalas', 'Mutton', 'Rice', 'Soft Drinks'],
 ['Breads & Buns',
  'Chocolates',
  'Dals & Pulses',
  'Fish',
  'Fresh Fruits',
  'Mutton',
  'Organic Fruits',
  'Soft Drinks',
  'Spices'],
 ['Health Drinks', 'Rice'],
 ['Edible Oil & Ghee', 'Fish'],
 ['Soft Drinks'],
 ['Biscuits', 'Mutton', 'Noodles', 'Organic Vegetables', 'Soft Drinks'],
 ['Biscuits', 'Chicken', 'Health Drinks', 'Mutton', 'Spices'],
 ['Biscuits',
  'Cakes',
  'Fresh Fruits',
  'Mutton',
  'Noodles',
  'Organic Vegetables',
  'Spices'],
 ['Biscuits', 'Fresh Vegetables', 'Spices'],
 ['Breads & Buns', 'Cakes', 'Chocolates', 'Noodles', 'Soft Drinks'],
 ['Cakes', 'Eggs', 'Masalas', 'Noodles'],
 ['Cakes',
  'Dals & Pulses',
  'Eggs',
  'Fresh Fruits',
  'Health Drinks',
  'Masalas',
  'Organic Fruits',
  'Organic Vegetables'],
 ['Biscuits', 'Breads & Buns', 'Cookies', 'Dals & Pulses'],
 ['Biscuits', 'Cookies', 'Fresh Fruits', 'Mutton', 'Rice'],
 ['Atta & Flour',
  'Cookies',
  'Dals & Pulses',
  'Eggs',
  'Fresh Fruits',
  'Health Drinks',
  'Noodles',
  'Organic Vegetables',
  'Rice',
  'Soft Drinks'],
 ['Breads & Buns'],
 ['Biscuits', 'Cakes', 'Edible Oil & Ghee'],
 ['Cookies', 'Spices'],
 ['Fish', 'Masalas', 'Spices'],
 ['Cakes', 'Mutton', 'Organic Staples'],
 ['Atta & Flour',
  'Cakes',
  'Dals & Pulses',
  'Noodles',
  'Soft Drinks',
  'Spices'],
 ['Noodles', 'Spices'],
 ['Fish', 'Health Drinks', 'Masalas'],
 ['Atta & Flour', 'Biscuits', 'Cakes', 'Health Drinks'],
 ['Chicken', 'Soft Drinks'],
 ['Cakes', 'Dals & Pulses', 'Eggs', 'Noodles', 'Organic Vegetables'],
 ['Soft Drinks'],
 ['Soft Drinks'],
 ['Rice'],
 ['Fresh Fruits', 'Health Drinks'],
 ['Spices'],
 ['Cookies', 'Dals & Pulses'],
 ['Edible Oil & Ghee', 'Spices'],
 ['Cookies', 'Eggs', 'Spices'],
 ['Biscuits', 'Chocolates'],
 ['Noodles'],
 ['Eggs', 'Fresh Fruits', 'Fresh Vegetables', 'Masalas', 'Organic Fruits'],
 ['Dals & Pulses',
  'Eggs',
  'Fresh Fruits',
  'Health Drinks',
  'Noodles',
  'Organic Fruits',
  'Organic Staples',
  'Soft Drinks'],
 ['Breads & Buns'],
 ['Health Drinks'],
 ['Breads & Buns', 'Cookies', 'Edible Oil & Ghee', 'Rice'],
 ['Breads & Buns', 'Fresh Fruits', 'Health Drinks', 'Masalas'],
 ['Eggs',
  'Fresh Fruits',
  'Fresh Vegetables',
  'Health Drinks',
  'Mutton',
  'Noodles'],
 ['Chocolates', 'Fresh Vegetables', 'Masalas', 'Noodles'],
 ['Biscuits',
  'Chocolates',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Health Drinks',
  'Organic Staples'],
 ['Chicken', 'Dals & Pulses', 'Fresh Vegetables', 'Mutton', 'Organic Fruits'],
 ['Biscuits',
  'Cakes',
  'Chocolates',
  'Cookies',
  'Dals & Pulses',
  'Health Drinks',
  'Soft Drinks'],
 ['Breads & Buns', 'Chocolates', 'Cookies', 'Health Drinks', 'Mutton'],
 ['Breads & Buns', 'Organic Vegetables', 'Soft Drinks'],
 ['Atta & Flour',
  'Chocolates',
  'Health Drinks',
  'Masalas',
  'Mutton',
  'Organic Staples'],
 ['Cakes',
  'Chocolates',
  'Cookies',
  'Fresh Vegetables',
  'Health Drinks',
  'Mutton',
  'Noodles',
  'Soft Drinks'],
 ['Noodles'],
 ['Atta & Flour', 'Breads & Buns', 'Organic Fruits', 'Soft Drinks'],
 ['Cakes', 'Chocolates', 'Eggs', 'Noodles'],
 ['Health Drinks', 'Masalas'],
 ['Health Drinks'],
 ['Cookies', 'Edible Oil & Ghee', 'Health Drinks', 'Spices'],
 ['Chocolates', 'Edible Oil & Ghee', 'Organic Fruits', 'Organic Vegetables'],
 ['Cakes',
  'Cookies',
  'Dals & Pulses',
  'Fish',
  'Fresh Fruits',
  'Health Drinks',
  'Masalas',
  'Organic Vegetables',
  'Soft Drinks'],
 ['Atta & Flour',
  'Breads & Buns',
  'Eggs',
  'Health Drinks',
  'Noodles',
  'Soft Drinks'],
 ['Atta & Flour',
  'Chocolates',
  'Fish',
  'Health Drinks',
  'Masalas',
  'Mutton',
  'Organic Fruits',
  'Organic Staples'],
 ['Atta & Flour',
  'Breads & Buns',
  'Cookies',
  'Eggs',
  'Health Drinks',
  'Noodles',
  'Organic Vegetables'],
 ['Organic Staples'],
 ['Soft Drinks'],
 ['Health Drinks', 'Mutton', 'Soft Drinks'],
 ['Chocolates', 'Masalas'],
 ['Cakes', 'Fish', 'Health Drinks', 'Masalas', 'Organic Vegetables'],
 ['Chocolates'],
 ['Breads & Buns',
  'Cookies',
  'Edible Oil & Ghee',
  'Eggs',
  'Fresh Fruits',
  'Organic Staples',
  'Soft Drinks'],
 ['Masalas'],
 ['Breads & Buns', 'Cookies', 'Mutton'],
 ['Atta & Flour', 'Breads & Buns', 'Chicken', 'Fresh Fruits'],
 ['Chocolates'],
 ['Chicken', 'Health Drinks', 'Mutton', 'Organic Vegetables', 'Rice'],
 ['Chocolates'],
 ['Edible Oil & Ghee', 'Health Drinks'],
 ['Rice', 'Soft Drinks'],
 ['Cakes', 'Fish', 'Soft Drinks'],
 ['Breads & Buns', 'Cookies', 'Health Drinks', 'Mutton', 'Noodles'],
 ['Chocolates', 'Fish', 'Masalas', 'Noodles', 'Organic Fruits'],
 ['Dals & Pulses', 'Health Drinks', 'Rice'],
 ['Breads & Buns',
  'Chocolates',
  'Edible Oil & Ghee',
  'Eggs',
  'Organic Fruits',
  'Organic Vegetables'],
 ['Atta & Flour', 'Fish', 'Organic Fruits', 'Organic Vegetables'],
 ['Chicken'],
 ['Dals & Pulses'],
 ['Cakes', 'Cookies', 'Health Drinks', 'Organic Vegetables'],
 ['Edible Oil & Ghee', 'Eggs', 'Fish', 'Health Drinks', 'Spices'],
 ['Mutton', 'Soft Drinks'],
 ['Cakes',
  'Chicken',
  'Chocolates',
  'Health Drinks',
  'Organic Staples',
  'Organic Vegetables',
  'Soft Drinks'],
 ['Fish', 'Organic Fruits', 'Rice', 'Spices'],
 ['Chocolates', 'Dals & Pulses'],
 ['Cookies', 'Fish', 'Health Drinks', 'Noodles'],
 ['Chicken', 'Cookies', 'Edible Oil & Ghee', 'Masalas', 'Rice', 'Soft Drinks'],
 ['Cakes', 'Edible Oil & Ghee', 'Noodles', 'Rice', 'Spices'],
 ['Mutton', 'Noodles'],
 ['Fish', 'Mutton'],
 ['Breads & Buns', 'Chocolates', 'Spices'],
 ['Chocolates',
  'Cookies',
  'Edible Oil & Ghee',
  'Fresh Fruits',
  'Mutton',
  'Organic Staples'],
 ['Chicken', 'Health Drinks', 'Masalas', 'Noodles', 'Soft Drinks'],
 ['Cakes', 'Eggs', 'Noodles'],
 ['Atta & Flour', 'Health Drinks', 'Spices'],
 ['Biscuits', 'Eggs', 'Health Drinks', 'Mutton', 'Organic Fruits', 'Rice'],
 ['Atta & Flour',
  'Chocolates',
  'Cookies',
  'Eggs',
  'Health Drinks',
  'Noodles',
  'Rice',
  'Soft Drinks'],
 ['Chicken', 'Edible Oil & Ghee', 'Health Drinks', 'Rice'],
 ['Atta & Flour',
  'Cookies',
  'Noodles',
  'Organic Staples',
  'Organic Vegetables',
  'Rice',
  'Soft Drinks'],
 ['Atta & Flour',
  'Breads & Buns',
  'Cakes',
  'Chicken',
  'Dals & Pulses',
  'Edible Oil & Ghee',
  'Eggs',
  'Fish',
  'Masalas',
  'Mutton',
  'Noodles',
  'Organic Fruits',
  'Organic Vegetables'],
 ['Fish', 'Noodles', 'Soft Drinks'],
 ['Biscuits'],
 ['Biscuits', 'Cookies', 'Masalas', 'Soft Drinks'],
 ['Breads & Buns', 'Edible Oil & Ghee'],
 ['Health Drinks', 'Mutton', 'Spices'],
 ['Dals & Pulses', 'Fish'],
 ['Atta & Flour', 'Chocolates', 'Edible Oil & Ghee', 'Eggs'],
 ['Fresh Fruits', 'Fresh Vegetables', 'Mutton'],
 ['Breads & Buns',
  'Edible Oil & Ghee',
  'Fresh Fruits',
  'Fresh Vegetables',
  'Noodles',
  'Organic Fruits',
  'Spices'],

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Replaces the true ands false and makes turns them into 1 or 0(one-hot encoding)
# Columns = items, rows = baskets

from mlxtend.preprocessing import TransactionEncoder
a = TransactionEncoder()
a_data = a.fit(data).transform(data)
df = pd.DataFrame(a_data, columns=a.columns_)

# Turn False/True into 0/1
df = df.replace(False, 0)
df = df.replace(True, 1)

df

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/tmp/ipython-input-187660132.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(True, 1)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,Atta & Flour,Biscuits,Breads & Buns,Cakes,Chicken,Chocolates,Cookies,Dals & Pulses,Edible Oil & Ghee,Eggs,...,Health Drinks,Masalas,Mutton,Noodles,Organic Fruits,Organic Staples,Organic Vegetables,Rice,Soft Drinks,Spices
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2263,1,0,0,0,0,0,1,0,1,1,...,0,1,0,1,0,0,0,0,0,0
2264,1,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
2265,1,0,0,0,0,0,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
2266,1,1,0,0,0,1,0,0,1,0,...,1,1,0,1,0,1,0,0,0,0
2267,0,1,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Finds the items groups that show up often
df = apriori(df, min_support=0.05, use_colnames=True)
df

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

     support                            itemsets
0   0.145062                      (Atta & Flour)
1   0.184303                          (Biscuits)
2   0.194885                     (Breads & Buns)
3   0.178571                             (Cakes)
4   0.138889                           (Chicken)
5   0.196649                        (Chocolates)
6   0.201940                           (Cookies)
7   0.140212                     (Dals & Pulses)
8   0.177249                 (Edible Oil & Ghee)
9   0.151675                              (Eggs)
10  0.150353                              (Fish)
11  0.148148                      (Fresh Fruits)
12  0.145062                  (Fresh Vegetables)
13  0.270282                     (Health Drinks)
14  0.181658                           (Masalas)
15  0.156966                            (Mutton)
16  0.192681                           (Noodles)
17  0.137566                    (Organic Fruits)
18  0.150353                   (Organic Staples)
19  0.138007                (Organic Vegetables)
20  0.134480                              (Rice)
21  0.259700                       (Soft Drinks)
22  0.174603                            (Spices)
23  0.053792           (Biscuits, Health Drinks)
24  0.054233             (Soft Drinks, Biscuits)
25  0.059965      (Breads & Buns, Health Drinks)
26  0.064374        (Soft Drinks, Breads & Buns)
27  0.051587              (Cakes, Health Drinks)
28  0.050705                (Soft Drinks, Cakes)
29  0.054674         (Chocolates, Health Drinks)
30  0.055996           (Soft Drinks, Chocolates)
31  0.060406            (Cookies, Health Drinks)
32  0.055115              (Soft Drinks, Cookies)
33  0.053792  (Health Drinks, Edible Oil & Ghee)
34  0.059083            (Masalas, Health Drinks)
35  0.050265            (Noodles, Health Drinks)
36  0.050265    (Health Drinks, Organic Staples)
37  0.081570        (Soft Drinks, Health Drinks)
38  0.052910             (Spices, Health Drinks)
39  0.053792              (Soft Drinks, Masalas)
40  0.054674              (Soft Drinks, Noodles)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# confidence rule.
df_ar = association_rules(df, metric="confidence", min_threshold=0.30)
df_ar

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Breads & Buns),(Health Drinks),0.194885,0.270282,0.059965,0.307692,1.138411,1.0,0.007291,1.054037,0.151013,0.147987,0.051267,0.264776
1,(Breads & Buns),(Soft Drinks),0.194885,0.259700,0.064374,0.330317,1.271916,1.0,0.013762,1.105448,0.265533,0.164972,0.095389,0.289097
2,(Edible Oil & Ghee),(Health Drinks),0.177249,0.270282,0.053792,0.303483,1.122836,1.0,0.005885,1.047666,0.132966,0.136618,0.045498,0.251252
3,(Masalas),(Health Drinks),0.181658,0.270282,0.059083,0.325243,1.203345,1.0,0.009984,1.081452,0.206494,0.150393,0.075318,0.271920
4,(Organic Staples),(Health Drinks),0.150353,0.270282,0.050265,0.334311,1.236896,1.0,0.009627,1.096184,0.225416,0.135714,0.087744,0.260141
5,(Soft Drinks),(Health Drinks),0.259700,0.270282,0.081570,0.314092,1.162088,1.0,0.011377,1.063871,0.188410,0.181908,0.060036,0.307943
6,(Health Drinks),(Soft Drinks),0.270282,0.259700,0.081570,0.301794,1.162088,1.0,0.011377,1.060289,0.191142,0.181908,0.056861,0.307943
7,(Spices),(Health Drinks),0.174603,0.270282,0.052910,0.303030,1.121163,1.0,0.005718,1.046986,0.130929,0.134983,0.044878,0.249394

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Lift rules
df_ar = association_rules(df, metric="lift", min_threshold=1)
df_ar

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Biscuits),(Health Drinks),0.184303,0.270282,0.053792,0.291866,1.079857,1.0,0.003978,1.030480,0.090660,0.134213,0.029578,0.245444
1,(Health Drinks),(Biscuits),0.270282,0.184303,0.053792,0.199021,1.079857,1.0,0.003978,1.018375,0.101342,0.134213,0.018043,0.245444
2,(Soft Drinks),(Biscuits),0.259700,0.184303,0.054233,0.208829,1.133070,1.0,0.006369,1.030999,0.158641,0.139140,0.030067,0.251543
3,(Biscuits),(Soft Drinks),0.184303,0.259700,0.054233,0.294258,1.133070,1.0,0.006369,1.048967,0.143977,0.139140,0.046681,0.251543
4,(Breads & Buns),(Health Drinks),0.194885,0.270282,0.059965,0.307692,1.138411,1.0,0.007291,1.054037,0.151013,0.147987,0.051267,0.264776
5,(Health Drinks),(Breads & Buns),0.270282,0.194885,0.059965,0.221860,1.138411,1.0,0.007291,1.034665,0.166616,0.147987,0.033504,0.264776
6,(Soft Drinks),(Breads & Buns),0.259700,0.194885,0.064374,0.247878,1.271916,1.0,0.013762,1.070457,0.288781,0.164972,0.065820,0.289097
7,(Breads & Buns),(Soft Drinks),0.194885,0.259700,0.064374,0.330317,1.271916,1.0,0.013762,1.105448,0.265533,0.164972,0.095389,0.289097
8,(Cakes),(Health Drinks),0.178571,0.270282,0.051587,0.288889,1.068842,1.0,0.003323,1.026166,0.078410,0.129856,0.025498,0.239877
9,(Health Drinks),(Cakes),0.270282,0.178571,0.051587,0.190865,1.068842,1.0,0.003323,1.015193,0.088264,0.129856,0.014966,0.239877
10,(Soft Drinks),(Cakes),0.259700,0.178571,0.050705,0.195246,1.093379,1.0,0.004330,1.020720,0.115364,0.130830,0.020300,0.239598
11,(Cakes),(Soft Drinks),0.178571,0.259700,0.050705,0.283951,1.093379,1.0,0.004330,1.033867,0.103970,0.130830,0.032758,0.239598
12,(Chocolates),(Health Drinks),0.196649,0.270282,0.054674,0.278027,1.028654,1.0,0.001523,1.010727,0.034675,0.132620,0.010613,0.240155
13,(Health Drinks),(Chocolates),0.270282,0.196649,0.054674,0.202284,1.028654,1.0,0.001523,1.007064,0.038174,0.132620,0.007014,0.240155
14,(Soft Drinks),(Chocolates),0.259700,0.196649,0.055996,0.215620,1.096470,1.0,0.004927,1.024186,0.118847,0.139868,0.023614,0.250187
15,(Chocolates),(Soft Drinks),0.196649,0.259700,0.055996,0.284753,1.096470,1.0,0.004927,1.035027,0.109519,0.139868,0.033842,0.250187
16,(Cookies),(Health Drinks),0.201940,0.270282,0.060406,0.299127,1.106720,1.0,0.005825,1.041155,0.120829,0.146681,0.039528,0.261309
17,(Health Drinks),(Cookies),0.270282,0.201940,0.060406,0.223491,1.106720,1.0,0.005825,1.027754,0.132145,0.146681,0.027004,0.261309
18,(Soft Drinks),(Cookies),0.259700,0.201940,0.055115,0.212224,1.050926,1.0,0.002671,1.013055,0.065458,0.135575,0.012886,0.242575
19,(Cookies),(Soft Drinks),0.201940,0.259700,0.055115,0.272926,1.050926,1.0,0.002671,1.018190,0.060720,0.135575,0.017865,0.242575
20,(Health Drinks),(Edible Oil & Ghee),0.270282,0.177249,0.053792,0.199021,1.122836,1.0,0.005885,1.027182,0.149918,0.136618,0.026463,0.251252
21,(Edible Oil & Ghee),(Health Drinks),0.177249,0.270282,0.053792,0.303483,1.122836,1.0,0.005885,1.047666,0.132966,0.136618,0.045498,0.251252
22,(Masalas),(Health Drinks),0.181658,0.270282,0.059083,0.325243,1.203345,1.0,0.009984,1.081452,0.206494,0.150393,0.075318,0.271920
23,(Health Drinks),(Masalas),0.270282,0.181658,0.059083,0.218597,1.203345,1.0,0.009984,1.047273,0.231573,0.150393,0.045139,0.271920
24,(Health Drinks),(Organic Staples),0.270282,0.150353,0.050265,0.185971,1.236896,1.0,0.009627,1.043755,0.262464,0.135714,0.041921,0.260141
25,(Organic Staples),(Health Drinks),0.150353,0.270282,0.050265,0.334311,1.236896,1.0,0.009627,1.096184,0.225416,0.135714,0.087744,0.260141
26,(Soft Drinks),(Health Drinks),0.259700,0.270282,0.081570,0.314092,1.162088,1.0,0.011377,1.063871,0.188410,0.181908,0.060036,0.307943
27,(Health Drinks),(Soft Drinks),0.270282,0.259700,0.081570,0.301794,1.162088,1.0,0.011377,1.060289,0.191142,0.181908,0.056861,0.307943
28,(Spices),(Health Drinks),0.174603,0.270282,0.052910,0.303030,1.121163,1.0,0.005718,1.046986,0.130929,0.134983,0.044878,0.249394
29,(Health Drinks),(Spices),0.270282,0.174603,0.052910,0.195759,1.121163,1.0,0.005718,1.026305,0.148097,0.134983,0.025631,0.249394
30,(Soft Drinks),(Masalas),0.259700,0.181658,0.053792,0.207131,1.140225,1.0,0.006615,1.032127,0.166122,0.138794,0.031127,0.251624
31,(Masalas),(Soft Drinks),0.181658,0.259700,0.053792,0.296117,1.140225,1.0,0.006615,1.051736,0.150279,0.138794,0.049191,0.251624
32,(Soft Drinks),(Noodles),0.259700,0.192681,0.054674,0.210526,1.092617,1.0,0.004634,1.022604,0.114503,0.137472,0.022105,0.247140
33,(Noodles),(Soft Drinks),0.192681,0.259700,0.054674,0.283753,1.092617,1.0,0.004634,1.033582,0.104997,0.137472,0.032490,0.247140

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Conviction rules
df_ar = association_rules(df, metric="conviction", min_threshold=1.0)
df_ar

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Health Drinks),(Biscuits),0.270282,0.184303,0.053792,0.199021,1.079857,1.0,0.003978,1.018375,0.101342,0.134213,0.018043,0.245444
1,(Biscuits),(Health Drinks),0.184303,0.270282,0.053792,0.291866,1.079857,1.0,0.003978,1.030480,0.090660,0.134213,0.029578,0.245444
2,(Biscuits),(Soft Drinks),0.184303,0.259700,0.054233,0.294258,1.133070,1.0,0.006369,1.048967,0.143977,0.139140,0.046681,0.251543
3,(Soft Drinks),(Biscuits),0.259700,0.184303,0.054233,0.208829,1.133070,1.0,0.006369,1.030999,0.158641,0.139140,0.030067,0.251543
4,(Breads & Buns),(Health Drinks),0.194885,0.270282,0.059965,0.307692,1.138411,1.0,0.007291,1.054037,0.151013,0.147987,0.051267,0.264776
5,(Health Drinks),(Breads & Buns),0.270282,0.194885,0.059965,0.221860,1.138411,1.0,0.007291,1.034665,0.166616,0.147987,0.033504,0.264776
6,(Breads & Buns),(Soft Drinks),0.194885,0.259700,0.064374,0.330317,1.271916,1.0,0.013762,1.105448,0.265533,0.164972,0.095389,0.289097
7,(Soft Drinks),(Breads & Buns),0.259700,0.194885,0.064374,0.247878,1.271916,1.0,0.013762,1.070457,0.288781,0.164972,0.065820,0.289097
8,(Health Drinks),(Cakes),0.270282,0.178571,0.051587,0.190865,1.068842,1.0,0.003323,1.015193,0.088264,0.129856,0.014966,0.239877
9,(Cakes),(Health Drinks),0.178571,0.270282,0.051587,0.288889,1.068842,1.0,0.003323,1.026166,0.078410,0.129856,0.025498,0.239877
10,(Soft Drinks),(Cakes),0.259700,0.178571,0.050705,0.195246,1.093379,1.0,0.004330,1.020720,0.115364,0.130830,0.020300,0.239598
11,(Cakes),(Soft Drinks),0.178571,0.259700,0.050705,0.283951,1.093379,1.0,0.004330,1.033867,0.103970,0.130830,0.032758,0.239598
12,(Chocolates),(Health Drinks),0.196649,0.270282,0.054674,0.278027,1.028654,1.0,0.001523,1.010727,0.034675,0.132620,0.010613,0.240155
13,(Health Drinks),(Chocolates),0.270282,0.196649,0.054674,0.202284,1.028654,1.0,0.001523,1.007064,0.038174,0.132620,0.007014,0.240155
14,(Chocolates),(Soft Drinks),0.196649,0.259700,0.055996,0.284753,1.096470,1.0,0.004927,1.035027,0.109519,0.139868,0.033842,0.250187
15,(Soft Drinks),(Chocolates),0.259700,0.196649,0.055996,0.215620,1.096470,1.0,0.004927,1.024186,0.118847,0.139868,0.023614,0.250187
16,(Health Drinks),(Cookies),0.270282,0.201940,0.060406,0.223491,1.106720,1.0,0.005825,1.027754,0.132145,0.146681,0.027004,0.261309
17,(Cookies),(Health Drinks),0.201940,0.270282,0.060406,0.299127,1.106720,1.0,0.005825,1.041155,0.120829,0.146681,0.039528,0.261309
18,(Soft Drinks),(Cookies),0.259700,0.201940,0.055115,0.212224,1.050926,1.0,0.002671,1.013055,0.065458,0.135575,0.012886,0.242575
19,(Cookies),(Soft Drinks),0.201940,0.259700,0.055115,0.272926,1.050926,1.0,0.002671,1.018190,0.060720,0.135575,0.017865,0.242575
20,(Health Drinks),(Edible Oil & Ghee),0.270282,0.177249,0.053792,0.199021,1.122836,1.0,0.005885,1.027182,0.149918,0.136618,0.026463,0.251252
21,(Edible Oil & Ghee),(Health Drinks),0.177249,0.270282,0.053792,0.303483,1.122836,1.0,0.005885,1.047666,0.132966,0.136618,0.045498,0.251252
22,(Masalas),(Health Drinks),0.181658,0.270282,0.059083,0.325243,1.203345,1.0,0.009984,1.081452,0.206494,0.150393,0.075318,0.271920
23,(Health Drinks),(Masalas),0.270282,0.181658,0.059083,0.218597,1.203345,1.0,0.009984,1.047273,0.231573,0.150393,0.045139,0.271920
24,(Organic Staples),(Health Drinks),0.150353,0.270282,0.050265,0.334311,1.236896,1.0,0.009627,1.096184,0.225416,0.135714,0.087744,0.260141
25,(Health Drinks),(Organic Staples),0.270282,0.150353,0.050265,0.185971,1.236896,1.0,0.009627,1.043755,0.262464,0.135714,0.041921,0.260141
26,(Health Drinks),(Soft Drinks),0.270282,0.259700,0.081570,0.301794,1.162088,1.0,0.011377,1.060289,0.191142,0.181908,0.056861,0.307943
27,(Soft Drinks),(Health Drinks),0.259700,0.270282,0.081570,0.314092,1.162088,1.0,0.011377,1.063871,0.188410,0.181908,0.060036,0.307943
28,(Spices),(Health Drinks),0.174603,0.270282,0.052910,0.303030,1.121163,1.0,0.005718,1.046986,0.130929,0.134983,0.044878,0.249394
29,(Health Drinks),(Spices),0.270282,0.174603,0.052910,0.195759,1.121163,1.0,0.005718,1.026305,0.148097,0.134983,0.025631,0.249394
30,(Masalas),(Soft Drinks),0.181658,0.259700,0.053792,0.296117,1.140225,1.0,0.006615,1.051736,0.150279,0.138794,0.049191,0.251624
31,(Soft Drinks),(Masalas),0.259700,0.181658,0.053792,0.207131,1.140225,1.0,0.006615,1.032127,0.166122,0.138794,0.031127,0.251624
32,(Noodles),(Soft Drinks),0.192681,0.259700,0.054674,0.283753,1.092617,1.0,0.004634,1.033582,0.104997,0.137472,0.032490,0.247140
33,(Soft Drinks),(Noodles),0.259700,0.192681,0.054674,0.210526,1.092617,1.0,0.004634,1.022604,0.114503,0.137472,0.022105,0.247140

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

The Supermart dataset contains orders placed by customers on a grocery app. We grouped the data by customers and months, then converted the column into a list. We then transformed the list with one-hot encoding to represent each transaction. We viewed the calculations of support, confidence, lift, and conviction to view any purchase behaviors or patterns with each product/purchase. The most frequent item that was purchased was healthy drinks with a value of .27. The probability of organic staples and health drinks being purchased was at a high confidence level of 33 and implies that if a person buys organic staples there is a 33% chance that a healthy drink will be purchased. We can see a positive correlation with soft drinks and bread being purchased with a lift of 1.27 and are more likely to be bough together. By looking at the conviction rule, we can see that bread and soft drinks are positively associated, and both of these items directly impact each other with a conviction of 1.1.